### ISSUE TITLE
Link to ASD Linux broken

### ISSUE THREAD

**Issue by Akeboshiwind** [kiss-community/website#11]
There's an extra comma included in the url here:
https://github.com/kiss-community/website/commit/8839cba3e56147559347dd2126a7f16766761a22#diff-ea4e171b4cf3f3d36429c8ad29f20bbdf25fa3dc03c69c1d0baeb615e6ba3582R158

Not sure how nessaccary it is, but I thought I'd point it out 😅

**Comment by dilyn-corner** [comment]
Gah. Every time... 

tyty 36b9bebe325dff0259231094796aae94fb81de00
