### ISSUE TITLE
RSS broken in Thunderbird

### ISSUE THREAD

**Issue by michalsieron** [kiss-community/website#12]
It seems that since article [20200506a](https://k1sslinux.org/news/20200506a), `<guid>` in feed entry contains trailing slash.
I guess that Thunderbird uses them to navigate to articles, because it tries to open one ending with a slash.
Previous articles did not contain it and they work fine.

I don't know about other clients, but even if they work it seems weird to have this slash when `<link>` doesn't.

**Comment by dilyn-corner** [comment]
If this is an issue for the new official website's RSS feed as well (kisslinux.xyz), You should also make an issue here https://github.com/kisslinux/website -- future plans for k1sslinux.org involve the site being repurposed and this problem will be solved "a different way".
